CREATE TABLE clientes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    representante_id INT NOT NULL,
    tipo_pessoa ENUM('F','J') NOT NULL,
    cpf_cnpj VARCHAR(18) NOT NULL,
    ie_rg VARCHAR(20) DEFAULT NULL,
    nome VARCHAR(150) NOT NULL,
    nome_fantasia VARCHAR(150) DEFAULT NULL,
    data_fundacao DATE DEFAULT NULL,
    telefone VARCHAR(20) DEFAULT NULL,
    celular VARCHAR(20) DEFAULT NULL,
    email VARCHAR(100) DEFAULT NULL,
    logradouro VARCHAR(100) DEFAULT NULL,
    numero VARCHAR(10) DEFAULT NULL,
    complemento VARCHAR(50) DEFAULT NULL,
    bairro VARCHAR(50) DEFAULT NULL,
    cep VARCHAR(10) DEFAULT NULL,
    estado CHAR(2) DEFAULT NULL,
    municipio VARCHAR(80) DEFAULT NULL,
    observacoes TEXT DEFAULT NULL,
    ativo TINYINT(1) DEFAULT 1,
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (representante_id) REFERENCES representantes(id) ON DELETE CASCADE
);